### ISSUE TITLE
How can I use emit inside router?

### ISSUE THREAD

**Issue by ncornejo** [Mohsin05/Sockets-Express-Generator#1]
thanks for the good example of socket.io implementation in Express

but how can I use emit inside router.get/post?

**Comment by Mohsin05** [comment]
Sorry, for the late response. if you want to use sockets in any page. 
Lets say you want to use sockets in post.html then just include the socket.io script at the end of page before the closing of body tag. 
`<script src="/socket.io/socket.io.js"></script>
`

and then use socket.emit to emit msg into the div. 

`<script>
    $(function () {
        var socket = io();
        $('form').submit(function(){
            socket.emit('chat message', $('#m').val());
            $('#m').val('');
            return false;
        });
        socket.on('chat message', function(msg){
            $('#messages').append($('<li>').text(msg));
        });
    });
</script>`
